// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<WPI_TalonSRX> RobotMap::driverSubSystemFrontLeft;
std::shared_ptr<WPI_TalonSRX> RobotMap::driverSubSystemFrontRight;
std::shared_ptr<WPI_VictorSPX> RobotMap::driverSubSystemBackLeft;
std::shared_ptr<WPI_VictorSPX> RobotMap::driverSubSystemBackRight;
std::shared_ptr<frc::RobotDrive> RobotMap::driverSubSystemRobotDrive;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    driverSubSystemFrontLeft.reset(new WPI_TalonSRX(1));
    
    
    driverSubSystemFrontRight.reset(new WPI_TalonSRX(2));
    
    
    driverSubSystemBackLeft.reset(new WPI_VictorSPX(3));
    
    
    driverSubSystemBackRight.reset(new WPI_VictorSPX(4));
    
    
    driverSubSystemRobotDrive.reset(new frc::RobotDrive(driverSubSystemFrontLeft, driverSubSystemBackLeft,
              driverSubSystemFrontRight, driverSubSystemBackRight));
    
    driverSubSystemRobotDrive->SetSafetyEnabled(false);
        driverSubSystemRobotDrive->SetExpiration(0.1);
        driverSubSystemRobotDrive->SetSensitivity(0.5);
        driverSubSystemRobotDrive->SetMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
