// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseSubFrontLeftTalen;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseSubFrontRightTalen;
std::shared_ptr<WPI_VictorSPX> RobotMap::driveBaseSubBackLeftTalen;
std::shared_ptr<WPI_VictorSPX> RobotMap::driveBaseSubBackRightTalen;
std::shared_ptr<frc::RobotDrive> RobotMap::driveBaseSubRobotDrive;
std::shared_ptr<WPI_TalonSRX> RobotMap::shooterSubsystemShooterTalen;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    driveBaseSubFrontLeftTalen.reset(new WPI_TalonSRX(1));
    
    
    driveBaseSubFrontRightTalen.reset(new WPI_TalonSRX(2));
    
    
    driveBaseSubBackLeftTalen.reset(new WPI_VictorSPX(3));
    
    
    driveBaseSubBackRightTalen.reset(new WPI_VictorSPX(4));
    
    
    driveBaseSubRobotDrive.reset(new frc::RobotDrive(driveBaseSubFrontLeftTalen, driveBaseSubBackLeftTalen,
              driveBaseSubFrontRightTalen, driveBaseSubBackRightTalen));
    
    driveBaseSubRobotDrive->SetSafetyEnabled(false);
        driveBaseSubRobotDrive->SetExpiration(0.1);
        driveBaseSubRobotDrive->SetSensitivity(0.5);
        driveBaseSubRobotDrive->SetMaxOutput(1.0);

    shooterSubsystemShooterTalen.reset(new WPI_TalonSRX(5));
    
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
